name: ml_in_prod_capstone
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - click=7.0
  - flask=1.1.1
  - itsdangerous=1.1.0
  - jinja2=2.11.1
  - joblib=0.14.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=9.0.1
  - libffi=3.2.1
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - llvm-openmp=9.0.1
  - markupsafe=1.1.1
  - ncurses=6.1
  - nose=1.3.7
  - numpy=1.18.1
  - openssl=1.1.1d
  - pandas=1.0.1
  - pip=20.0.2
  - python=3.7.3
  - python-dateutil=2.8.1
  - pyyaml=3.13
  - pytz=2019.3
  - readline=8.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - setuptools=45.2.0
  - six=1.14.0
  - sqlite=3.30.1
  - tk=8.6.10
  - werkzeug=1.0.0
  - wheel=0.34.2
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - boto3==1.12.0
    - botocore==1.15.0
    - cachetools==4.0.0
    - chardet==3.0.4
    - docutils==0.15.2
    - filelock==3.0.12
    - gast==0.2.2
    - google-auth==1.11.2
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.1.8
    - grpcio==1.27.2
    - h5py==2.10.0
    - idna==2.8
    - jmespath==0.9.4
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.2.1
    - oauthlib==3.1.0
    - opt-einsum==3.1.0
    - protobuf==3.11.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - regex==2020.1.8
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - s3transfer==0.3.3
    - sacremoses==0.0.38
    - sentencepiece==0.1.85
    - tensorboard==2.1.0
    - tensorflow==2.1.0
    - tensorflow-estimator==2.1.0
    - termcolor==1.1.0
    - tokenizers==0.0.11
    - tqdm==4.42.1
    - transformers==2.4.1
    - urllib3==1.25.8
    - wrapt==1.11.2

